app/api/urls.py
from django.urls import path, re_path

from .views import *


urlpatterns = [
    re_path('likes/(?P<post_id>\d+)$', LikesView.as_view())
]

app/news/urls.py
from django.urls import path, re_path

from news_django.settings import DEBUG
from .views import *
from .api import *


ajax = [
    path('api/news', ajax_load_more_news, name='ajax_load_news'),
    path('api/like', ajax_like, name="ajax_like"),
]

urlpatterns = [
    path('', index),
    path('new_post/', new_post),
    path('my_posts/', my_posts),
    re_path(r'^my_posts/edit/id(?P<post_id>\d+)$', edit_post),
    re_path(r'^posts/id(?P<post_id>\d+)$', view_post)
] + ajax

if DEBUG:
    urlpatterns = [
        path('show/', show, name='show'),
        path('js/', js, name='js')
    ] + urlpatterns

app/news_django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from news.views import *
from .settings import MEDIA_URL, MEDIA_ROOT


def to_news(_):
    return redirect('/news/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('auth/', include('authorize.urls')),
    path('profile/', include('user_profile.urls')),
    path('api/v1/', include('api.urls')),
    path('', to_news),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

app/news/models.py
import os
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


def path_and_rename(instance, filename):
    upload_to = f'posts/{timezone.now().strftime("%Y/%m/%d/")}'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to=path_and_rename, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    last_edit_time = models.DateTimeField(auto_now_add=True)
    is_posted = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag', blank=True)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ('-creation_date', 'title')


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='like_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=2000)
    creation_date = models.DateTimeField(auto_now_add=True)
    is_edited = models.BooleanField(default=False)

    is_visible = models.BooleanField(default=True)


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_like_user')


class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriber_user')
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE)
    notifications = models.BooleanField(default=False)


class Read(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='read_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    read_time = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'
        ordering = ('title',)

    def __str__(self):
        return self.title


class PageToken(models.Model):
    token = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="token_user")
    expired = models.DateTimeField()

app/news/forms.py
from django import forms

from .models import Tag


class TagSelectionForm(forms.Form):
    categories = forms.ModelMultipleChoiceField(Tag.objects, required=False, label=False,
                                                widget=forms.CheckboxSelectMultiple(attrs={'class': 'tag_checkbox'}))


class SearchForm(TagSelectionForm):
    search = forms.CharField(label=None,
                             widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'placeholder': 'Поиск по новостям'}),
                             required=False
                             )

    field_order = ['search', 'categories']


class PostForm(TagSelectionForm):
    title = forms.CharField(label='Название новости',
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название'}),
                            min_length=3, max_length=200)
    content = forms.CharField(label='Содержание новости',
                              widget=forms.Textarea(attrs={'class': 'form-control',
                                                           'placeholder': 'Введите содержание новости'}),
                              min_length=10, max_length=3000)
    image = forms.ImageField(label='Картинка (Необязательно)',
                             widget=forms.FileInput(attrs={'class': 'form-control'}),
                             required=False)

    field_order = ['title', 'content', 'image', 'categories']

app/news/views.py
import os

from django.shortcuts import render
from django.http import HttpResponseRedirect as redirect
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.uploadedfile import TemporaryUploadedFile
from django.core.exceptions import ObjectDoesNotExist

from .forms import PostForm, TagSelectionForm, SearchForm
from .models import Post, Tag, Like
from .util import LATEST_MAX_POSTS, LIKED_MAX_POSTS, MAIN_MAX_POSTS
from .util import user_token, get_posts_for_user, check_user_token_valid, check_cookie


def get_tag_link(form, match=False):
    match = "&match=1" if match else ''
    return f'filter={",".join(map(str, form.cleaned_data.get("categories")))}{match}'


# debug
def show(request):
    raise Exception


def js(request):
    return render(request, 'news/js.html')


# views
def index(request):
    form = SearchForm()
    token = user_token(request.user)

    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            return redirect(f'/news/search?{get_tag_link(form, "fsort" in request.POST.keys())}')

    latest_news = Post.objects.filter(is_posted=True).order_by('-creation_date').all()[:LATEST_MAX_POSTS]
    if request.user.is_authenticated:
        liked_news = [
            like.post for like in Like.objects.filter(user=request.user).order_by('-id').all()[:LIKED_MAX_POSTS]
        ]
    else:
        liked_news = None
    main_posts = get_posts_for_user(request.user)[:MAIN_MAX_POSTS]
    data = {
        'form': form,
        'latest': latest_news,
        'liked': liked_news,
        'main_posts': main_posts,
    }
    response = render(request, 'news/main_posts.html', context=data)
    check_cookie(request, response, token)
    return response


def view_post(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except ObjectDoesNotExist:
        return redirect('/news/')
    token = user_token(request.user)

    data = {
        'form': None,
        'post': post,
    }

    response = render(request, 'news/view_post.html', context=data)
    check_cookie(request, response, token)
    return response


@login_required
def my_posts(request):
    form = TagSelectionForm()
    list_posts = []
    posts = Post.objects.filter(author=request.user).all()
    if request.method == 'POST':
        form = TagSelectionForm(request.POST)
        print(request.POST.keys())
        if form.is_valid():
            # fsort in request means it's a match search
            return redirect(f"/news/my_posts?{get_tag_link(form, 'fsort' in request.POST.keys())}")
    if 'filter' in request.GET.keys():
        tag_str = request.GET.get('filter').split(',')
        tags = []
        for tag in Tag.objects.all():
            if tag.__str__() in tag_str:
                tags.append(tag)
        form = TagSelectionForm(initial={
            'categories': tags,
        })
        if tags:
            for post in posts:
                post_tags = post.tags.all()
                checks = [tag in post_tags for tag in tags]
                check = all(checks) if request.GET.get('match') else any(checks)
                if check:
                    list_posts.append(post)
            if not list_posts:
                # made for showing no posts if filter goes 0 posts
                posts = None
    data = {
        'posts': list_posts or posts,
        'form': form,
    }

    return render(request, 'news/my_posts.html', context=data)


@login_required
def edit_post(request, post_id):
    def delete_post_image(image):
        try:
            os.remove(image.path)
        except Exception as e:
            print(f'[ERROR] Deleting file: {image.path}, {e.__str__()}')

    try:
        post = Post.objects.get(pk=post_id)
    except ObjectDoesNotExist:
        return redirect('/news/my_posts')
    if post.author != request.user and not request.user.is_staff:
        messages.error(request, 'У вас нет доступа для редактирования этой новости')
        return redirect('/news/my_posts')
    form = PostForm(initial={
        'title': post.title,
        'content': post.content,
        'categories': post.tags.all(),
    })
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            f_data = form.cleaned_data
            post.title = f_data.get('title')
            post.content = f_data.get('content')

            if request.FILES.get('image'):
                if post.image:
                    delete_post_image(post.image)
                post.image = request.FILES.get('image')

            tags = f_data.get('categories')
            if list(post.tags.all()) != list(tags):
                post.tags.clear()
                [post.tags.add(tag) for tag in tags]

            post.last_edit_time = timezone.now()
            if any([req in request.POST.keys() for req in ['post', 'hide', 'delete']]):
                if 'delete' in request.POST.keys():
                    if post.image:
                        delete_post_image(post.image)
                    post.delete()
                    messages.info(request, f'Новость с ID: {post_id} успешно была удалена')
                    return redirect('/news/my_posts')
                post.is_posted = 'post' in request.POST.keys()
            post.save()
            messages.success(request, f'Новость с ID: {post_id} успешно была отредактирована')
            return redirect('/news/my_posts')
    data = {
        'form': form,
        'edit_mode': True,
        'is_posted': post.is_posted,
    }

    return render(request, 'news/post.html', context=data)


@login_required
def new_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST)
        if any([i in request.POST.keys() for i in ('save', 'post')]):
            if form.is_valid():
                data = form.cleaned_data
                _new = Post(
                    title=data.get('title'),
                    content=data.get('content'),
                    author=request.user,
                )
                _new.is_posted = 'post' in request.POST.keys()
                _new.save()
                if request.FILES.get('image'):
                    file: TemporaryUploadedFile = request.FILES.get('image')
                    _new.image = file
                    _new.save()
                for tag in data.get('categories'):
                    _new.tags.add(tag)
                if 'post' in request.POST.keys():
                    messages.success(request, 'Ваша запись была отпубликована')
                else:
                    messages.success(request, 'Ваша запись была сохранена')
                return redirect('/news/my_posts')
        else:
            messages.error(request, 'Неизвестное действие')

    data = {
        'form': form,
        'edit_mode': False,
        'is_posted': False,
    }
    return render(request, 'news/post.html', context=data)

app/news/templates/news/main_posts.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}
{% block head %}
    <title>News</title>
    <link rel="stylesheet" href="{% static "news/css/main_posts.css" %}?{{ reload }}">
    <script src="{% static "news/js/tags.js" %}?{{reload}}"></script>
    <script src="{% static "news/js/main_posts.js" %}?{{reload}}"></script>
{% endblock %}
{% block container %}
    <div id="content" style="display: none;">
        <p id="user_id">{% if request.user.is_authenticated %}{{ request.user.id }}{% else %}-1{% endif %}</p>
        <p id="page_user_token">{{token}}</p>
    </div>
    <div class="main-container">
        <div class="search-bar">

        </div>
        <div class="main-content">
            <div class="main-line">
                {% for item in main_posts %}
                <div class="card" post_id="{{item.id}}">
                    <div class="card-header">
                      <div class="user-info">
                        <a href="/news/users/id{{item.author.id}}"><img src="/static/user_profile/img/profile_images/{{item.author.id}}.png" class="card-avatar avatar-validation"></a>
                        <div style="margin-left: 10px;">
                            <a href="/news/users/id{{item.author.id}}"><p>{{item.author.username}}</p></a>
                            <p>Отпубликовано: <span class="card-publish-time">{{item.creation_date|date:"d:m:Y:H:i:s"}}</span></p>
                        </div>
                    </div>
                      <div class="right-pannel">
                        actions
                      </div>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{item.title}}</h5>
                      <p class="card-text">{{item.content}}</p>
                      <a href="/news/posts/id{{item.id}}" class="btn btn-primary">Посмотреть новость</a>
                    </div>
                    <div class="card-footer">
                        {% if user.is_authenticated %}
                        <div class="likes">
                            {% if item.like_set.all|has_user:user %}
                            <div class="like-button active" id="like-button">
                                <img src="/static/news/img/like_active.png" alt="" width="32" height="32">
                            </div>
                            {% else %}
                            <div class="like-button" id="like-button" >
                                <img src="/static/news/img/like.png" alt="" width="32" height="32">
                            </div>
                            {% endif %}
                            <span style="margin-left: 10px;">{{ item.like_set.all|length }}</span>
                        </div>
                        <div class="comments">
                            <a class="comm-button" href="/news/posts/id{{item.id}}#comment">
                                <img src="{% static "news/img/comment.png" %}?{{reload}}" alt="com">
                            </a>
                            <span class="comm-count">{{ item.comment_set.all|length }}</span>
                        </div>
                        <div class="reposts">
                            reps
                        </div>
                        {% else %}
                        <span><a href="/auth/login">Авторизуйтесь</a> для дополнительный действий</span>
                        {% endif %}
                    </div>
                </div>
                  <br>
                {% endfor %}
                <div class="more">
                    <button class="btn btn-primary">Показать больше</button>
                </div>
            </div>
            <div class="right-panel">
                <div class="liked-news">
                    <h5>Вам понравилось</h5>
                    {% if user.is_authenticated %}
                        {% if liked %}
                            {% for item in liked %}
                                <div class="liked">
                                    <div class="right-card">
                                        <div class="image">
                                            <img src=
                                            "
                                            {% if item.image %}
                                                {{ item.image.url }}
                                            {% else %}
                                                {% static "news/img/no-image.jpg"%}
                                            {% endif %}
                                            " 
                                            alt="" width="75" height="40">
                                        </div>
                                        <div class="title">
                                            <a href="/news/posts/id{{item.id}}">{{ item.title|truncatechars:35 }}</a>
                                        </div>
                                        <div class="likes">
                                            <p>{{ item.like_set.all|length }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p class="liked-center"> Вы пока не лайкнули ни одну новость.</p>
                        {% endif %}
                    {% else %}
                        <p class="liked-center">Для просмотра понравившихся новостей вы должны быть <a href="/auth/login">авторизованы</a>.</p>
                    {% endif %}
                </div>
                <div class="newest-news">
                    <h5>Последние новости</h5>
                    {% for item in latest %}
                        <div class="right-card">
                            <div class="image">
                                <img src=
                                "
                                {% if item.image %}
                                    {{ item.image.url }}
                                {% else %}
                                    {% static "news/img/no-image.jpg"%}
                                {% endif %}
                                " 
                                alt="" width="75" height="40">
                            </div>
                            <div class="title">
                                <a href="/news/posts/id{{item.id}}">{{ item.title|truncatechars:35 }}</a>
                            </div>
                            <div class="likes">
                                <p>{{ item.like_set.all|length }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/news/templates/news/my_posts.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}
{% block head %}
    <title>My Posts</title>
    <link rel="stylesheet" href="{% static "news/css/my_posts.css" %}?{{ reload }}">
    <script src="{% static "news/js/tags.js" %}?{{reload}}"></script>
{% endblock %}
{% block container %}
    <div class="main-container">
        {% include "news/include/tags.html "%}
        <div class="posts-container">
            <h2 style="text-align: center;">Ваши записи</h2>
            <div class="create-new">
                <h3><a href="/news/new_post">Создать новую запись</a></h3>
            </div>
            {% include "include/messages.html"%}
            {% if posts %}
                <div class="cards">
                    {% for post in posts %}
                        <div class="card">
                            {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top card-image" alt="No image">
                            {% else %}
                            <img src="{% static "news/img/no-image.jpg"%}" class="card-img-top card-image" alt="No image">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-content">{{post.content|truncatechars:250}}</p>
                                <p>Статус новости: 
                                    {% if not post.is_posted %}
                                    <span style="color: red;">Не отпубликована</span>
                                    {% else %}
                                    <span style="color: green;">Отпубликована</span>
                                    {% endif %}
                                </p>
                                <p class="post-tags">Теги: 
                                    {% if post.tags.all %}
                                    <span>{{post.tags.all|join:", "}}</span>
                                    {% else %}
                                    <span>Нет</span>
                                    {% endif %}
                                </p>
                                <div class="card-time">
                                    <p class="card-text"><small class="text-muted">Дата создания: {{ post.creation_date }}</small></p>
                                    <p class="card-text"><small class="text-muted">Последнее редактирование: {{ post.last_edit_time|localtime }}</small></p>
                                </div>
                                <a href="/news/my_posts/edit/id{{post.id}}" class="btn btn-primary mt-3" style="text-decoration: none;">Редактировать</a>
                            </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <h4 class="no-posts">У вас пока нет ни одной записи. <a href="/news/new_post">Создать</a></h4>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/news/templates/news/post.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>New Post</title>
    <link rel="stylesheet" href="{% static "news/css/post.css" %}?{{ reload }}">
    <script src="{% static "news/js/tags.js" %}?{{reload}}"></script>
{% endblock %}
{% block container %}
    <div class="new_post">
        {% if not edit_mode %}
        <h2>Добавить новость</h2>
        {% else %}
        <h2>Изменить новость</h2>
        <h2><a href="/news/my_posts">Вернуться назад</a></h2>
        {% endif %}
        {% include "include/messages.html" %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="options">
                {% if not edit_mode %}
                <button type="submit" name="save" value="save" class="btn btn-secondary">Сохранить как черновик</button>
                {% else %}
                <button type="submit" name="delete" value="delete" class="btn btn-danger">Удалить новость</button>
                <button type="submit" name="update" value="update" class="btn btn-primary">Сохранить изменения</button>
                {% endif %}
                {% if not is_posted %}
                <button type="submit" name="post" value="post" class="btn btn-success">Отпубликовать новость</button>
                {% else %}
                <button type="submit" name="hide" value="hide" class="btn btn-secondary">Снять с публикации</button>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

app/news/templates/news/view_post.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>View Post</title>
    <link rel="stylesheet" href="{% static "news/css/view_post.css" %}?{{ reload }}">
    <script src="{% static "news/js/view_posts.js"%}?{{reload}}"></script>
{% endblock %}
{% block container %}
    <div class="post-card">
        <div class="post-header">

        </div>
        <h2 class="post-title">
            {{ post.title }}
        </h2>
        {% if post.image %}    
        <img src="{{ post.image.url }}" alt="">
        {% endif %}
        <p class="post-content">
            {{ post.content }}
        </p>
    </div>

{% endblock %}